### ISSUE TITLE
dbname seems to be missing in irrexplorer_config.yml.dist

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#5]
I get this when starting IRRExplorer locally:

htj@pyrite:~/src/irrexplorer$ python irrexplorer.py 
Traceback (most recent call last):
  File "irrexplorer.py", line 205, in <module>
    worker = NRTMWorker(feedconfig, lookup_queues[name], result_queues[name])
  File "irrexplorer.py", line 125, in **init**
    self.dbname = feedconfig['dbname']
KeyError: 'dbname'

I've added some manual dbname field to in my irrexplorer_config.yml, which seems to fix this. Currently just using altdb, apnic, etc. Not sure if that is right, or if it matter. If it is right, it could just the entry name instead of a seperate field.

**Comment by job** [comment]
Can you paste your current irrexplorer_config.yml file?

**Comment by htj** [comment]
Now it looks like this:

databases:
    - altdb:
        - serial: 'ftp://ftp.radb.net/radb/dbase/ALTDB.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/altdb.db.gz'
        - nrtmhost: 'whois.altdb.net'
        - nrtmport: 43
        - dbname: 'altdb'
    - apnic:
        - serial: 'ftp://ftp.radb.net/radb/dbase/APNIC.CURRENTSERIAL'
        - dump': 'ftp://ftp.radb.net/radb/dbase/apnic.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'apnic'
    - level3:
        - serial: 'ftp://ftp.radb.net/radb/dbase/LEVEL3.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/level3.db.gz'
        - nrtmhost: rr.ntt.net
        - nrtmport: 43
        - dbname: 'level3'
    - radb:
        - serial: 'ftp://ftp.radb.net/radb/dbase/RADB.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/radb.db.gz'
        - nrtmhost: 'whois.radb.net'
        - nrtmport: 43
        - dbname: 'radb'

Which is the one from the distribution with added dbname fields. This seems to work (well, it gets me further, there is some wonky stuff going on with nrtm.client).

**Comment by job** [comment]
It could be that you are not white-listed from your IP to set up a NRTM session with any of these mirrors.

**Comment by htj** [comment]
Eh, what. I cannot get that to make sense.

It works with the above. The issue is that the irrexplorer_config.yml.dist file does not include the dbname fields.

**Comment by job** [comment]
This is the config that irrexplorer.nlnog.net uses:

```
databases:
    - afrinic:
        - serial: 'ftp://ftp.afrinic.net/dbase/AFRINIC.CURRENTSERIAL'
        - dump: 'ftp://ftp.afrinic.net/dbase/afrinic.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'AFRINIC'
    - altdb:
        - serial: 'ftp://ftp.radb.net/radb/dbase/ALTDB.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/altdb.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'ALTDB'
    - apnic:
        - serial: 'APNIC.CURRENTSERIAL'
        - dump: 'apnic.db'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'APNIC'
    - arin:
        - serial: 'ftp://ftp.radb.net/radb/dbase/ARIN.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/arin.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'ARIN'
    - bboi:
        - serial: 'ftp://ftp.radb.net/radb/dbase/BBOI.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/bboi.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'BBOI'
    - bell:
        - serial: 'ftp://ftp.radb.net/radb/dbase/BELL.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/bell.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'BELL'
    - gt:
        - serial: 'ftp://ftp.radb.net/radb/dbase/GT.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/gt.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'GT'
    - jpirr:
        - serial: 'ftp://ftp.radb.net/radb/dbase/JPIRR.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/jpirr.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'JPIRR'
    - level3:
        - serial: 'ftp://ftp.radb.net/radb/dbase/LEVEL3.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/level3.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'LEVEL3'
    - nttcom:
        - serial: 'ftp://ftp.radb.net/radb/dbase/NTTCOM.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/nttcom.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'NTTCOM'
    - radb:
        - serial: 'ftp://ftp.radb.net/radb/dbase/RADB.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/radb.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'RADB'
    - rgnet:
        - serial: 'ftp://ftp.radb.net/radb/dbase/RGNET.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/rgnet.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'RGNET'
    - ripe:
        - serial: 'RIPE.CURRENTSERIAL'
        - dump: 'ripe.db'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'RIPE'
    - savvis:
        - serial: 'ftp://ftp.radb.net/radb/dbase/SAVVIS.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/savvis.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'SAVVIS'
    - tc:
        - serial: 'ftp://ftp.radb.net/radb/dbase/TC.CURRENTSERIAL'
        - dump: 'ftp://ftp.radb.net/radb/dbase/tc.db.gz'
        - nrtmhost: 'rr.ntt.net'
        - nrtmport: 43
        - dbname: 'TC'
```
